version: 0.4.{build}

platform: Any CPU
configuration: Release

pull_requests:
  do_not_increment_build_number: true

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

artifacts:
  - path: '**\Bridge.AWS*.nupkg'

install:
  appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

before_build:
  - ps: |
      nuget restore src/Bridge.AWS.sln
      $content = (Get-Content src/Bridge.AWS.nuspec) 
      $content = $content -replace '\$version\$',${env:APPVEYOR_BUILD_VERSION}
      $content | Out-File src/Bridge.AWS.nuspec
  
build:
  project: src/Bridge.AWS.sln
  verbosity: normal
  publish_nuget: true

deploy:
  provider: NuGet
  api_key:
    secure: WrL2uPCxsKi6WaC+BqV9F6NzgFqtc8P9rtTOrTmcNtVg8YMbbniVxWglwGau0byD
  skip_symbols: true
  artifact: /.*\.nupkg/